In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]


In [3]:
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
array1 = np.array(l1)
array2 = np.array(l2)

In [5]:
array1

array([1, 2, 3, 4])

In [6]:
array2

array([5, 6, 7, 8])

In [7]:
type(array1)

numpy.ndarray

In [8]:
array1.shape

(4,)

In [9]:
a= np.array([[[1,2,3,4]]])

In [10]:
a.shape

(1, 1, 4)

In [11]:
b= np.array([[1],
             [2],
             [3],
             [4]])

In [12]:
b.shape

(4, 1)

In [13]:
c= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [14]:
c.shape

(3, 3)

In [15]:
d=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
c+d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
c-d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
c*d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
c/d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
b*a

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]]])

In [23]:
np.dot(c,d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
np.dot(b,a)

array([[[ 1,  2,  3,  4]],

       [[ 2,  4,  6,  8]],

       [[ 3,  6,  9, 12]],

       [[ 4,  8, 12, 16]]])

In [25]:
np.dot(a,b)

array([[[30]]])

In [26]:
np.transpose(a)

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [27]:
a.T

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [28]:
np.sum(a)

10

In [29]:
np.max(a)

4

In [30]:
e = np.reshape(d,(1,9))

In [31]:
e

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
f = np.reshape(c,(1,-1))

In [33]:
f

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
A = np.random.randint(10,100,size=(5,5))

In [35]:
A

array([[26, 43, 33, 93, 97],
       [52, 20, 49, 22, 88],
       [43, 31, 20, 33, 80],
       [72, 71, 53, 89, 92],
       [20, 98, 62, 43, 48]])

In [36]:
A[2,3]

33

In [37]:
##array sclicing

In [38]:
#A[rows,cols]

In [39]:
A[2:5,2:4]

array([[20, 33],
       [53, 89],
       [62, 43]])

In [40]:
A[2,]

array([43, 31, 20, 33, 80])

In [41]:
A.shape

(5, 5)

In [42]:
c.shape

(3, 3)

In [43]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A

array([[26, 43, 33, 93, 97],
       [52, 20, 49, 22, 88],
       [43, 31, 20, 33, 80],
       [72, 71, 53, 89, 92],
       [20, 98, 62, 43, 48]])

In [45]:
a

array([[[1, 2, 3, 4]]])

In [46]:
A**2

array([[ 676, 1849, 1089, 8649, 9409],
       [2704,  400, 2401,  484, 7744],
       [1849,  961,  400, 1089, 6400],
       [5184, 5041, 2809, 7921, 8464],
       [ 400, 9604, 3844, 1849, 2304]], dtype=int32)

In [47]:
a

array([[[1, 2, 3, 4]]])

In [48]:
a+b

array([[[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]]])

In [49]:
g = np.array([1,2,3,4])

In [50]:
g

array([1, 2, 3, 4])

In [51]:
h = np.array([[1,2,3,4],[1,2,3,4]])

In [52]:
h

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [53]:
g+h

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [54]:
pa =np.array([[1],[2]])

In [55]:
pa

array([[1],
       [2]])

In [56]:
pb = np.array([[5],[3]])

In [57]:
pb

array([[5],
       [3]])

In [58]:
x = pa-pb

In [59]:
x

array([[-4],
       [-1]])

In [60]:
x**2

array([[16],
       [ 1]], dtype=int32)

In [61]:
def distance(pA,pB):
    return np.sum((pB-pA)**2)**0.5

In [62]:
pB=np.array([5,6,7,8,9,10])
pA=np.array([7,8,9,0,10,11])
distance(pA,pB)

8.831760866327848

In [63]:
np.sin(90)

0.8939966636005579